<center><img src="https://is1-ssl.mzstatic.com/image/thumb/Purple122/v4/05/e7/67/05e76784-3364-b535-7e20-b3f4946a56b6/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/434x0w.webp" style="height:150px"></center>

# Introduction

Vous êtes un groupe d'hackers malveillants qui a pu récupérer des données clients d'une compagnie d'assurance. Cette compagnie d'assurance a de très mauvaises pratiques de protection des données et les données que vous avez réussi à récupérer contiennent des informations extrêmement sensibles comme le numéro de carte de crédit du client.

Néanmoins, ces données ne contiennent pas le nom et prénom de la personne, informations indispensables pour utiliser leur carte de crédit pour faire des achats sur Internet, vous devez donc trouver cette information autre part.

Afin de remédier à ce problème, vous avez réussi à hacker les données du gouvernement regroupant tous les foyers fiscaux de France, ce qui vous permettrait d'identifier les clients de la compagnie d'assurance si vous êtes malins. Un hacker de votre équipe a réussi à filtrer les foyers fiscaux pour qu'ils ne contiennent que les foyers des clients de l'assurance, ce qui vous simplifiera la tâche plus tard.

# Données

Vous disposez de trois jeux de données : 
* `"clients_exo.csv"` : Les données client volées de la compagnie d'assurance.
* `"foyers_df.csv"`: Les données des foyers fiscaux filtrées pour ne contenir que les foyers des clients de l'assurance.
* `"foyers_zipcode.json"` : Un dictionnaire vous permettant de relier un foyer fiscal au département dans lequel le foyer réside.


# Objectif

À l'aide des jeux de données fournis et de votre intelligence, vous devez matcher les numéros de carte de crédit des clients avec leur nom et prénom présents dans les données de foyers fiscaux.

Vous devez nous rendre un fichier csv dont la structure est la suivante:

|    | CreditCardNumber    | FullName          |
|---:|:--------------------|:------------------|
|  0 | 1111-2222-3333-4444 | Pierre Adeikalam  |
|  1 | 2222-1111-3333-4444 | Ahmed Besbes      |
|  2 | 3333-1111-2222-4444 | Benjamin Lebreton |
|  3 | 2222-2222-2222-2222 | Léa Couturier     |
|  4 | 1234-5678-9012-3456 | Nadir Abdou       |

À vous de jouer!

In [2]:
import pandas as pd
import json

clients_exo = pd.read_csv("clients_exo.csv")
foyers_df = pd.read_csv("foyers_df.csv")

with open("foyers_zipcode.json", "r") as f:
    foyers_zipcode = json.load(f)

In [3]:
foyers_df

       foyer_id            FullName DateOfBirth
0             0         Célina Roux  1975-10-01
1             1  Antoinette Bonneau  1989-02-24
2             1       Robert Bonnin  2022-11-13
3             2   Maurice Couturier  1955-06-04
4             2     Michelle Hoarau  1959-07-12
...         ...                 ...         ...
32292     12381  Jacqueline Perrier  1990-06-20
32293     12381     Xavier Fontaine  1993-09-26
32294     12381   Éléonore Fontaine  2012-10-21
32295     12382          Lucas Blin  1978-11-30
32296     12382       Michelle Blin  2020-03-05

[32297 rows x 3 columns]

In [4]:
clients_exo

,Married,NumberOfChildren,Address,CreditCardNumber,CreditCardExpirationDate,CreditCardCVC,DrivingLicenseDateObtained,DrivingLicenseAgeObtained
0,False,1,"646, boulevard de Munoz\r\n65761 Sainte Manon",2016-3231-5846-1119,4/25,957,2010-10-11,47.318275
1,False,0,rue Denis Maurice\r\n38494 Sainte Margot,4948-7746-5283-4627,9/24,626,1997-09-08,41.746749
2,False,2,boulevard Michelle Dupont\r\n14965 Nicolas-les...,2412-5676-4101-9638,5/24,139,2009-10-18,35.299110
3,True,2,"4, rue de Launay\r\n17389 Paul-les-Bains",4256-5129-1543-6145,9/24,748,1987-12-29,20.027379
4,True,1,"97, rue de Bertrand\r\n53561 Lopes",6842-1235-2306-5811,11/24,470,2016-11-21,31.997262
...,...,...,...,...,...,...,...,...
12378,False,1,chemin de Weiss\r\n92576 Gimenez,7880-2861-6329-5755,4/25,478,2004-03-05,19.383984
12379,False,1,"31, avenue de Gomez\r\n87882 Schmitt",7681-8792-5636-8059,8/24,661,2010-03-01,36.440794
12380,True,2,"16, avenue de Guillou\r\n87459 Chevalier",4593-1884-1164-6668,7/24,726,2018-01-04,34.417522
12381,True,0,"5, rue Deschamps\r\n37720 Cohen",5502-8754-4385-7920,12/25,716,2014-01-14,21.106092
12382,False,3,"65, chemin de Rolland\r\n77791 Gautier",9937-1115-6967-2894,7/25,382,2004-12-09,22.809035

In [5]:
foyers_zipcode.keys()

dict_keys(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '97'])

In [ ]:
# add zip code to clients_exo from address
def get_zipcode(address):
    try:
        return foyers_zipcode[address]
    except:
        return None
clients_exo["zipcode"] = clients_exo["address"].apply(get_zipcode)