<center><img src="https://is1-ssl.mzstatic.com/image/thumb/Purple122/v4/05/e7/67/05e76784-3364-b535-7e20-b3f4946a56b6/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/434x0w.webp" style="height:150px"></center>


# Introduction

Vous disposez d'un jeu de données décrivant des accidents de la route ayant eu lieu en janvier 2022. Ce jeu de données a été corrompu et vous devez vous débrouiller pour le réparer.


# Données

Vous disposez de deux jeux de données : 
* **`"accidents.csv"`** : Les données décrivant les conditions de l'accident.
* **`"vehicules.csv"`** : Les données décrivant les véhicules impliqués dans l'accident.

Voici une description de chaque champ présent dans ces fichiers:

**`"accidents.csv"`**:

* **`"Num_acc"`** : Identifiant unique de l'accident.
* **`"Date"`** : Date et heure de l'accident.
* **`"Conditions Lumineuses"`** : Si l'accident a eu lieu en journée ou pendant la nuit.
* **`"Conditions Atmosphériques"`** : Si l'accident a eu lieu sous la pluie ou en temps normal.
* **`"Etat Surface"`** : Si la surface de la route où a eu lieu l'accident était mouillée ou sèche.
* **`"Catégorie Route"`** : La catégorie de la route où l'accident s'est produit ("Voie Communale", "Route Nationale", "Route Départementale", "Autoroute").
* **`"Vitesse Maximale Autorisée"`** : La vitesse maximale autorisée sur la route où a eu lieu l'accident (30, 50, ... , 130).
* **`"Type Collision"`** : Comment les véhicules se sont percutés ("Par l'arrière", "Par le côté", "Frontale", "Autre").
* **`"Nombre Véhicules Impliqués"`** : Le nombre de véhicules impliqués dans l'accident.
* **`"Nombre Usagers Impliqués"`** : Le nombre de passagers présents dans les véhicules impliqués dans l'accident.
* **`"Gravité"`** : Vaut 1 s'il y a eu au moins une personne blessée à l'issue de l'accident, 0 si tout le monde s'en est sortie indemne.

**`"vehicules.csv"`**:

* **`"Num_acc"`** : Identifiant unique de l'accident.
* **`"Catégorie du véhicule"`** : La catégorie du véhicule impliqué dans l'accident ("Véhicule Léger", "Véhicule Utilitaire", "Motocyclette" ou "Byciclette").
* **`"Point de choc"`** : Le point d'impact sur le véhicule ("Avant", "Côté Gauche", "Côté Droit" ou "Arrière").
* **`"Nombre de passagers"`** : Le nombre de passagers présents dans le véhicule au moment de l'accident.
* **`"Obstacle heurté"`** : L'obstacle ou l'élément heurté lors de l'accident ("Véhicule", "Fossé", "Batiment ou Mobilier urbain" ou "Glissière").


# Objectif

À l'aide de vos compétences logiques et analytiques, vous devrez comprendre le contenu des données fournies et trouver des méthodes pour remplir les valeurs manquantes.

**Vous devrez nous remettre un fichier csv dont la structure est identique à celle du fichier `"accidents.csv"` et où vous aurez rempli les valeurs manquantes avec des valeurs appropriées.**

**À vous de jouer!**

In [2]:
import pandas as pd

accidents = pd.read_csv("accidents.csv")
vehicules = pd.read_csv("vehicules.csv")

In [11]:
accidents.head(20)

,Num_acc,Date,Conditions Lumineuses,Conditions Atmosphériques,Etat Surface,Catégorie Route,Vitesse Maximale Autorisée,Type Collision,Nombre Véhicules Impliqués,Nombre Usagers Impliqués,Gravité
0,0,2022-01-06 03:39:36,Nuit,Normal,Sec,NaN,80.0,Frontale,2.0,2.0,NaN
1,1,2022-01-04 05:36:20,Nuit,Pluie,Mouillé,Voie Communale,NaN,Par le coté,2.0,6.0,0.0
2,2,2022-01-13 16:38:18,Jour,Normal,Sec,Route Départementale,NaN,Par le coté,NaN,NaN,0.0
3,3,2022-01-22 18:07:11,Nuit,Normal,NaN,Voie Communale,NaN,Par le coté,2.0,6.0,0.0
4,4,2022-01-10 07:43:14,Nuit,Normal,NaN,Route Départementale,80.0,NaN,1.0,1.0,NaN
5,5,2022-01-04 19:52:29,Nuit,Pluie,Mouillé,Route Départementale,80.0,NaN,1.0,1.0,NaN
6,6,2022-01-29 05:40:02,Nuit,Normal,NaN,NaN,80.0,Par le coté,NaN,NaN,0.0
7,7,2022-01-17 17:08:12,NaN,NaN,Sec,Route Départementale,NaN,Frontale,2.0,2.0,0.0
8,8,2022-01-19 02:54:44,Nuit,Pluie,Mouillé,NaN,70.0,NaN,2.0,3.0,NaN
9,9,2022-01-13 19:33:13,Nuit,Normal,Sec,NaN,30.0,Frontale,2.0,NaN,0.0
10,10,2022-01-28 02:52:24,Nuit,Normal,Sec,NaN,50.0,Autre,1.0,3.0,0.0
11,11,2022-01-02 02:50:18,Nuit,Normal,NaN,NaN,50.0,Par le coté,NaN,4.0,0.0
12,12,2022-01-22 10:25:11,Jour,Normal,NaN,Route Départementale,NaN,Autre,1.0,1.0,0.0
13,13,2022-01-23 22:25:22,NaN,NaN,Sec,Route Départementale,NaN,Par le coté,2.0,7.0,0.0
14,14,2022-01-25 12:18:40,Jour,Normal,Sec,NaN,130.0,Autre,NaN,1.0,NaN
15,15,2022-01-13 23:28:10,Nuit,NaN,Sec,Voie Communale,30.0,Autre,NaN,1.0,NaN
16,16,2022-01-21 10:44:32,Jour,NaN,Sec,NaN,70.0,Autre,3.0,NaN,1.0
17,17,2022-01-20 16:22:34,NaN,Normal,Sec,Voie Communale,50.0,NaN,NaN,2.0,0.0
18,18,2022-01-17 04:51:48,Nuit,Normal,NaN,Route Nationale,NaN,Par le coté,2.0,2.0,1.0
19,19,2022-01-28 04:01:15,Nuit,Normal,NaN,Autoroute,130.0,Par l'arrière,2.0,2.0,0.0

In [4]:
vehicules.head()

,Num_acc,Catégorie du véhicule,Point de choc,Nombre de passagers,Obstacle heurté
0,0,Véhicule Léger,Avant,1,Véhicule
1,0,Véhicule Léger,Côté Gauche,1,Véhicule
2,1,Véhicule Léger,Avant,5,Véhicule
3,1,Véhicule Léger,Côté Droit,1,Véhicule
4,2,Bicyclette,Avant,1,Fossé

In [24]:
accidents2 = accidents.copy()
accidents2.head()

,Num_acc,Date,Conditions Lumineuses,Conditions Atmosphériques,Etat Surface,Catégorie Route,Vitesse Maximale Autorisée,Type Collision,Nombre Véhicules Impliqués,Nombre Usagers Impliqués,Gravité
0,0,2022-01-06 03:39:36,Nuit,Normal,Sec,NaN,80.0,Frontale,2.0,2.0,NaN
1,1,2022-01-04 05:36:20,Nuit,Pluie,Mouillé,Voie Communale,NaN,Par le coté,2.0,6.0,0.0
2,2,2022-01-13 16:38:18,Jour,Normal,Sec,Route Départementale,NaN,Par le coté,NaN,NaN,0.0
3,3,2022-01-22 18:07:11,Nuit,Normal,NaN,Voie Communale,NaN,Par le coté,2.0,6.0,0.0
4,4,2022-01-10 07:43:14,Nuit,Normal,NaN,Route Départementale,80.0,NaN,1.0,1.0,NaN

In [55]:
accidents2["Etat Surface"].unique()

array(['Sec', 'Mouillé', nan], dtype=object)

In [45]:
accidents2["Etat Surface"].isna()

0       False
1       False
2       False
3        True
4        True
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: Etat Surface, Length: 10000, dtype: bool

In [48]:
condition1 = (accidents2["Conditions Atmosphériques"]=="Normal") 
condition2 = (accidents2["Conditions Atmosphériques"]=="Pluie")
condition3 =  accidents2["Etat Surface"].isna()

In [53]:
accidents_normal = accidents2[accidents2["Conditions Atmosphériques"]=="Normal"]
accidents_normal["Etat Surface"] = accidents_normal["Etat Surface"].fillna("Sec")
accidents_normal

C:\Users\26236\AppData\Local\Temp\ipykernel_19224\384806716.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accidents_normal["Etat Surface"] = accidents_normal["Etat Surface"].fillna("Sec")

,Num_acc,Date,Conditions Lumineuses,Conditions Atmosphériques,Etat Surface,Catégorie Route,Vitesse Maximale Autorisée,Type Collision,Nombre Véhicules Impliqués,Nombre Usagers Impliqués,Gravité
0,0,2022-01-06 03:39:36,Nuit,Normal,Sec,NaN,80.0,Frontale,2.0,2.0,NaN
2,2,2022-01-13 16:38:18,Jour,Normal,Sec,Route Départementale,NaN,Par le coté,NaN,NaN,0.0
3,3,2022-01-22 18:07:11,Nuit,Normal,Sec,Voie Communale,NaN,Par le coté,2.0,6.0,0.0
4,4,2022-01-10 07:43:14,Nuit,Normal,Sec,Route Départementale,80.0,NaN,1.0,1.0,NaN
6,6,2022-01-29 05:40:02,Nuit,Normal,Sec,NaN,80.0,Par le coté,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...
9992,9992,2022-01-27 11:17:09,Jour,Normal,Sec,Voie Communale,50.0,Autre,1.0,NaN,0.0
9993,9993,2022-01-23 18:47:42,Nuit,Normal,Sec,NaN,50.0,Autre,NaN,NaN,0.0
9994,9994,2022-01-12 16:05:49,Jour,Normal,Sec,Autoroute,130.0,NaN,2.0,2.0,1.0
9995,9995,2022-01-21 07:10:12,Nuit,Normal,Sec,NaN,80.0,Par le coté,NaN,8.0,1.0
9996,9996,2022-01-23 14:28:52,NaN,Normal,Sec,NaN,70.0,NaN,1.0,1.0,0.0

In [56]:
accidents_pluie = accidents2[accidents2["Conditions Atmosphériques"]=="Pluie"]
accidents_pluie["Etat Surface"] = accidents_pluie["Etat Surface"].fillna("Mouillé")
accidents_pluie

C:\Users\26236\AppData\Local\Temp\ipykernel_19224\210300146.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accidents_pluie["Etat Surface"] = accidents_pluie["Etat Surface"].fillna("Mouillé")

,Num_acc,Date,Conditions Lumineuses,Conditions Atmosphériques,Etat Surface,Catégorie Route,Vitesse Maximale Autorisée,Type Collision,Nombre Véhicules Impliqués,Nombre Usagers Impliqués,Gravité
1,1,2022-01-04 05:36:20,Nuit,Pluie,Mouillé,Voie Communale,NaN,Par le coté,2.0,6.0,0.0
5,5,2022-01-04 19:52:29,Nuit,Pluie,Mouillé,Route Départementale,80.0,NaN,1.0,1.0,NaN
8,8,2022-01-19 02:54:44,Nuit,Pluie,Mouillé,NaN,70.0,NaN,2.0,3.0,NaN
20,20,2022-01-19 12:42:32,NaN,Pluie,Mouillé,NaN,70.0,Par le coté,2.0,NaN,NaN
22,22,2022-01-03 11:31:04,Jour,Pluie,Mouillé,NaN,80.0,Par le coté,2.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
9959,9959,2022-01-07 23:17:19,NaN,Pluie,Mouillé,Route Départementale,80.0,Par le coté,2.0,5.0,1.0
9964,9964,2022-01-08 23:26:04,Nuit,Pluie,Mouillé,Voie Communale,30.0,Frontale,2.0,2.0,NaN
9980,9980,2022-01-08 01:51:13,Nuit,Pluie,Mouillé,Voie Communale,NaN,NaN,1.0,3.0,0.0
9985,9985,2022-01-03 14:17:49,Jour,Pluie,Mouillé,NaN,70.0,Par l'arrière,2.0,5.0,0.0
9997,9997,2022-01-19 09:57:19,NaN,Pluie,Mouillé,NaN,90.0,Autre,NaN,3.0,1.0

In [57]:
accidents_nanLeft = accidents2[accidents2["Conditions Atmosphériques"].isna()]
accidents_nanLeft

,Num_acc,Date,Conditions Lumineuses,Conditions Atmosphériques,Etat Surface,Catégorie Route,Vitesse Maximale Autorisée,Type Collision,Nombre Véhicules Impliqués,Nombre Usagers Impliqués,Gravité
7,7,2022-01-17 17:08:12,NaN,NaN,Sec,Route Départementale,NaN,Frontale,2.0,2.0,0.0
13,13,2022-01-23 22:25:22,NaN,NaN,Sec,Route Départementale,NaN,Par le coté,2.0,7.0,0.0
15,15,2022-01-13 23:28:10,Nuit,NaN,Sec,Voie Communale,30.0,Autre,NaN,1.0,NaN
16,16,2022-01-21 10:44:32,Jour,NaN,Sec,NaN,70.0,Autre,3.0,NaN,1.0
26,26,2022-01-07 01:27:39,Nuit,NaN,Mouillé,Voie Communale,NaN,Par le coté,2.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
9987,9987,2022-01-31 23:31:15,Nuit,NaN,Sec,Voie Communale,NaN,Autre,1.0,2.0,NaN
9988,9988,2022-01-09 14:24:35,NaN,NaN,Mouillé,Voie Communale,NaN,NaN,NaN,NaN,0.0
9990,9990,2022-01-22 14:37:05,Jour,NaN,Sec,Voie Communale,50.0,NaN,2.0,2.0,NaN
9998,9998,2022-01-18 19:45:03,Nuit,NaN,Sec,Voie Communale,30.0,NaN,2.0,5.0,0.0
9999,9999,2022-01-25 18:55:11,Nuit,NaN,Sec,NaN,70.0,NaN,NaN,4.0,NaN

In [58]:
frame1 = [accidents_normal, accidents_pluie, accidents_nanLeft]

In [59]:
accidents_fill_fan = pd.concat(frame1)

In [68]:
accidents_fill_fan.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Num_acc                     10000 non-null  int64
 1   Date                        10000 non-null  object
 2   Conditions Lumineuses       7000 non-null   object
 3   Conditions Atmosphériques   7000 non-null   object
 4   Etat Surface                10000 non-null  object
 5   Catégorie Route             7000 non-null   object
 6   Vitesse Maximale Autorisée  7000 non-null   float64
 7   Type Collision              7000 non-null   object
 8   Nombre Véhicules Impliqués  7000 non-null   float64
 9   Nombre Usagers Impliqués    7000 non-null   float64
 10  Gravité                     7000 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 937.5+ KB

In [63]:
accidents_sec = accidents_fill_fan[accidents_fill_fan["Etat Surface"] == "Sec"]
accidents_sec["Conditions Atmosphériques"] = accidents_sec["Conditions Atmosphériques"].fillna("Normal")

C:\Users\26236\AppData\Local\Temp\ipykernel_19224\367666408.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accidents_sec["Conditions Atmosphériques"] = accidents_sec["Conditions Atmosphériques"].fillna("Normal")

In [65]:
accidents_mouille = accidents_fill_fan[accidents_fill_fan["Etat Surface"] == "Mouillé"]
accidents_mouille["Conditions Atmosphériques"] = accidents_mouille["Conditions Atmosphériques"].fillna("Pluie")

C:\Users\26236\AppData\Local\Temp\ipykernel_19224\2295867072.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  accidents_mouille["Conditions Atmosphériques"] = accidents_mouille["Conditions Atmosphériques"].fillna("Pluie")

In [69]:
frame2 = [accidents_sec, accidents_mouille]
accidents_fill_fan2 = pd.concat(frame2)

In [70]:
accidents_fill_fan2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9988
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Num_acc                     10000 non-null  int64
 1   Date                        10000 non-null  object
 2   Conditions Lumineuses       7000 non-null   object
 3   Conditions Atmosphériques   10000 non-null  object
 4   Etat Surface                10000 non-null  object
 5   Catégorie Route             7000 non-null   object
 6   Vitesse Maximale Autorisée  7000 non-null   float64
 7   Type Collision              7000 non-null   object
 8   Nombre Véhicules Impliqués  7000 non-null   float64
 9   Nombre Usagers Impliqués    7000 non-null   float64
 10  Gravité                     7000 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 937.5+ KB

In [60]:
accidents_fill_fan.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Num_acc                     10000 non-null  int64
 1   Date                        10000 non-null  object
 2   Conditions Lumineuses       7000 non-null   object
 3   Conditions Atmosphériques   7000 non-null   object
 4   Etat Surface                10000 non-null  object
 5   Catégorie Route             7000 non-null   object
 6   Vitesse Maximale Autorisée  7000 non-null   float64
 7   Type Collision              7000 non-null   object
 8   Nombre Véhicules Impliqués  7000 non-null   float64
 9   Nombre Usagers Impliqués    7000 non-null   float64
 10  Gravité                     7000 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 937.5+ KB

In [32]:
accidents2.isna().sum()

Num_acc                          0
Date                             0
Conditions Lumineuses         3000
Conditions Atmosphériques     3000
Etat Surface                  3000
Catégorie Route               3000
Vitesse Maximale Autorisée    3000
Type Collision                3000
Nombre Véhicules Impliqués    3000
Nombre Usagers Impliqués      3000
Gravité                       3000
dtype: int64

In [19]:
accidents2["Etat Surface"].isna().sum()

3000

In [20]:
accidents2["Etat Surface"]

0           Sec
1       Mouillé
2           Sec
3           NaN
4           NaN
         ...
9995        Sec
9996        Sec
9997    Mouillé
9998        Sec
9999        Sec
Name: Etat Surface, Length: 10000, dtype: object

In [21]:
# define fill in function
def fill_etat_surface(row):
    if pd.notna(row["Conditions Atmosphériques"]) and pd.isna(row["Etat Surface"]):
        return "Sec" if row["Conditions Atmosphériques"] == "Normal" else "Mouillé"
    else:
        pass
    
def fill_condition_atmo(row):
    if pd.notna(row["Etat Surface"]) and pd.isna(row["Conditions Atmosphériques"]):
        return "Normal" if row["Etat Surface"] == "Sec" else "Pluie"
    else:
        pass
accidents2["Etat Surface"] = accidents2.apply(fill_etat_surface, axis=1)
accidents2["Conditions Atmosphériques"] = accidents2.apply(fill_condition_atmo, axis = 1)

In [23]:
accidents2.isna().sum()

Num_acc                           0
Date                              0
Conditions Lumineuses          3000
Conditions Atmosphériques     10000
Etat Surface                   7000
Catégorie Route                3000
Vitesse Maximale Autorisée     3000
Type Collision                 3000
Nombre Véhicules Impliqués     3000
Nombre Usagers Impliqués       3000
Gravité                        3000
dtype: int64

In [13]:
accidents2.apply(fill_etat_surface, axis=1)

0           Sec
1       Mouillé
2           Sec
3           Sec
4           Sec
         ...
9995        Sec
9996        Sec
9997    Mouillé
9998       None
9999       None
Length: 10000, dtype: object

In [14]:
accidents2["Conditions Atmosphériques"]

0       Normal
1        Pluie
2       Normal
3       Normal
4       Normal
         ...
9995    Normal
9996    Normal
9997     Pluie
9998      None
9999      None
Name: Conditions Atmosphériques, Length: 10000, dtype: object

In [17]:
accidents2.head(20)

,Num_acc,Date,Conditions Lumineuses,Conditions Atmosphériques,Etat Surface,Catégorie Route,Vitesse Maximale Autorisée,Type Collision,Nombre Véhicules Impliqués,Nombre Usagers Impliqués,Gravité
0,0,2022-01-06 03:39:36,Nuit,Normal,Sec,NaN,80.0,Frontale,2.0,2.0,NaN
1,1,2022-01-04 05:36:20,Nuit,Pluie,Mouillé,Voie Communale,NaN,Par le coté,2.0,6.0,0.0
2,2,2022-01-13 16:38:18,Jour,Normal,Sec,Route Départementale,NaN,Par le coté,NaN,NaN,0.0
3,3,2022-01-22 18:07:11,Nuit,Normal,NaN,Voie Communale,NaN,Par le coté,2.0,6.0,0.0
4,4,2022-01-10 07:43:14,Nuit,Normal,NaN,Route Départementale,80.0,NaN,1.0,1.0,NaN
5,5,2022-01-04 19:52:29,Nuit,Pluie,Mouillé,Route Départementale,80.0,NaN,1.0,1.0,NaN
6,6,2022-01-29 05:40:02,Nuit,Normal,NaN,NaN,80.0,Par le coté,NaN,NaN,0.0
7,7,2022-01-17 17:08:12,NaN,NaN,Sec,Route Départementale,NaN,Frontale,2.0,2.0,0.0
8,8,2022-01-19 02:54:44,Nuit,Pluie,Mouillé,NaN,70.0,NaN,2.0,3.0,NaN
9,9,2022-01-13 19:33:13,Nuit,Normal,Sec,NaN,30.0,Frontale,2.0,NaN,0.0
10,10,2022-01-28 02:52:24,Nuit,Normal,Sec,NaN,50.0,Autre,1.0,3.0,0.0
11,11,2022-01-02 02:50:18,Nuit,Normal,NaN,NaN,50.0,Par le coté,NaN,4.0,0.0
12,12,2022-01-22 10:25:11,Jour,Normal,NaN,Route Départementale,NaN,Autre,1.0,1.0,0.0
13,13,2022-01-23 22:25:22,NaN,NaN,Sec,Route Départementale,NaN,Par le coté,2.0,7.0,0.0
14,14,2022-01-25 12:18:40,Jour,Normal,Sec,NaN,130.0,Autre,NaN,1.0,NaN
15,15,2022-01-13 23:28:10,Nuit,NaN,Sec,Voie Communale,30.0,Autre,NaN,1.0,NaN
16,16,2022-01-21 10:44:32,Jour,NaN,Sec,NaN,70.0,Autre,3.0,NaN,1.0
17,17,2022-01-20 16:22:34,NaN,Normal,Sec,Voie Communale,50.0,NaN,NaN,2.0,0.0
18,18,2022-01-17 04:51:48,Nuit,Normal,NaN,Route Nationale,NaN,Par le coté,2.0,2.0,1.0
19,19,2022-01-28 04:01:15,Nuit,Normal,NaN,Autoroute,130.0,Par l'arrière,2.0,2.0,0.0

In [5]:
## Pour remplir la colonne vitesse max autorisée:


vitesses = accidents[accidents["Catégorie Route"].notnull()][["Catégorie Route", "Vitesse Maximale Autorisée"]].drop_duplicates()
vitesses.dropna(inplace=True)

print(vitesses)

def replacing_function(x):
    if x == "Autoroute":
        return 130
    elif x == "Route Nationale":
        return 100
    elif x == "Route Départementale":
        return 75
    elif x == "Voie Communale":
        return (30+50)/2
    else:
        return None

accidents["Vitesse Maximale Autorisée"] = accidents["Catégorie Route"].apply(replacing_function)
accidents.head()

          Catégorie Route  Vitesse Maximale Autorisée
4    Route Départementale                        80.0
15         Voie Communale                        30.0
17         Voie Communale                        50.0
19              Autoroute                       130.0
24   Route Départementale                        70.0
176       Route Nationale                        90.0
203       Route Nationale                       110.0

,Num_acc,Date,Conditions Lumineuses,Conditions Atmosphériques,Etat Surface,Catégorie Route,Vitesse Maximale Autorisée,Type Collision,Nombre Véhicules Impliqués,Nombre Usagers Impliqués,Gravité
0,0,2022-01-06 03:39:36,Nuit,Normal,Sec,NaN,NaN,Frontale,2.0,2.0,NaN
1,1,2022-01-04 05:36:20,Nuit,Pluie,Mouillé,Voie Communale,40.0,Par le coté,2.0,6.0,0.0
2,2,2022-01-13 16:38:18,Jour,Normal,Sec,Route Départementale,75.0,Par le coté,NaN,NaN,0.0
3,3,2022-01-22 18:07:11,Nuit,Normal,NaN,Voie Communale,40.0,Par le coté,2.0,6.0,0.0
4,4,2022-01-10 07:43:14,Nuit,Normal,NaN,Route Départementale,75.0,NaN,1.0,1.0,NaN